// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoEWyl0ksya_N2e4B6PuwQfC9QcAvLYH8',
    appId: '1:223770597713:web:15a3bd72dcbcb066389b70',
    messagingSenderId: '223770597713',
    projectId: 'dermai-2d6b8',
    authDomain: 'dermai-2d6b8.firebaseapp.com',
    storageBucket: 'dermai-2d6b8.firebasestorage.app',
    measurementId: 'G-S48B1DXPWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsVRCt7xJ7FeCE7Hf8l1HEl1STEDPW9TY',
    appId: '1:223770597713:android:f176dd1909a164dd389b70',
    messagingSenderId: '223770597713',
    projectId: 'dermai-2d6b8',
    storageBucket: 'dermai-2d6b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNZ0Y4HJlwW0fRq4aLVzzRdlXKzexL9S4',
    appId: '1:223770597713:ios:02c527f5a8de0fb2389b70',
    messagingSenderId: '223770597713',
    projectId: 'dermai-2d6b8',
    storageBucket: 'dermai-2d6b8.firebasestorage.app',
    iosBundleId: 'com.example.dermaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNZ0Y4HJlwW0fRq4aLVzzRdlXKzexL9S4',
    appId: '1:223770597713:ios:02c527f5a8de0fb2389b70',
    messagingSenderId: '223770597713',
    projectId: 'dermai-2d6b8',
    storageBucket: 'dermai-2d6b8.firebasestorage.app',
    iosBundleId: 'com.example.dermaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoEWyl0ksya_N2e4B6PuwQfC9QcAvLYH8',
    appId: '1:223770597713:web:c7038fe16013fdfd389b70',
    messagingSenderId: '223770597713',
    projectId: 'dermai-2d6b8',
    authDomain: 'dermai-2d6b8.firebaseapp.com',
    storageBucket: 'dermai-2d6b8.firebasestorage.app',
    measurementId: 'G-ZV3DE153HB',
  );
}
